name: Documentation

on:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: technote-space/get-diff-action@v3
        with:
          PREFIX_FILTER: docs
          SUFFIX_FILTER: .md
          FILES: |
            README.md

      - name: Setup Node.js environment
        if: env.GIT_DIFF
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12"

      - name: Lint markdown files
        if: env.GIT_DIFF
        run: |
          npx markdownlint-cli ${{ env.GIT_DIFF }}
