name: NPM Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Needs to be a bit more than 1 otherwise it might fail to push
          # a new tag.
          # With `fetch-depth: 1` which is the default you might get
          # [remote rejected]   v0.x.x -> v0.x.y (shallow update not allowed)
          # in the GitHub Action.
          # So not sure what the number is but let's try something beyond 1.
          fetch-depth: 10

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2.1.2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install all yarn packages
        run: yarn --frozen-lockfile

      - name: Build the build
        run: |
          # What this does is it makes sure the built client is made for
          # doing CRUD work (e.g. previewing, toolbar, flaws UI, etc)
          export REACT_APP_CRUD_MODE=true

          # This makes sure the auth is disabled. I.e. the "Sign in" link
          # in the header. It also disables any XHR checks to the server's
          # whoami endpoint.
          export REACT_APP_DISABLE_AUTH=true

          yarn prepare-build

      - name: Dry-run publish to see which files are included
        run: |
          npm publish --access public --dry-run

      - name: Publish to npmjs
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
