name: Performance

on:
  pull_request:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Needed because of
          # https://github.com/GoogleChrome/lighthouse-ci/issues/172
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/checkout@v2
        with:
          repository: mdn/content
          path: mdn/content

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "12"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2.1.3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install all yarn packages
        run: |
          ./testing/scripts/yarn-install.sh

      - name: Build select important pages
        run: |
          # Remember, the mdn/content repo got cloned into `pwd` into a
          # sub-folder called "mdn/content"
          export CONTENT_ROOT=$(pwd)/mdn/content/files

          # Make sure it's set to something so that the build uses the
          # Google Analytics tag which is most realistic.
          export BUILD_GOOGLE_ANALYTICS_ACCOUNT=UA-00000000-0

          yarn prepare-build
          # BUILD_FOLDERSEARCH=mdn/kitchensink yarn build
          BUILD_FOLDERSEARCH=web/javascript/reference/global_objects/array/foreach yarn build

      - name: Serve and lhci
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          yarn start:static-server &
          sleep 1
          curl --retry-connrefused --retry 5 \
            http://localhost:5000/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach/ > /dev/null

          npm install -g @lhci/cli@next

          # Note, we can supply multiple `--collect.url=...` to have lhci test
          # a variety of URLs and then assume a average (or median?) across them.

          # All options for "collect" here:
          # https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#collect

          lhci autorun \
            --upload.target=temporary-public-storage \
            --collect.url="http://localhost:5000/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach/"

          # TODO (as of Oct 2020)
          # Once our Lighthouse score starts to not be so terrible, we can start
          # adding assertions here.
          # See https://github.com/GoogleChrome/lighthouse-ci/blob/master/docs/configuration.md#categories
